---
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
type: Opaque
stringData:
  username: test
  password: test
