---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/k3s/infra/capacitor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      environment: example
      cluster: example
  postBuild:
    substitute:
      cluster_subdomain: example.com
      ingress_class: traefik
  dependsOn:
    - name: traefik
