---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-k8s-stack
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/k3s/infra/victoria-metrics-k8s-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      env: example
      cluster_name: example
      cluster_subdomain: example.com
  dependsOn:
    - name: traefik
